apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: web
  labels:
    app: nginx-web
spec:
  type: ClusterIP
  selector:
    app: nginx-web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
